web:
  image: hugh/nginx
  volumes: 
  #   # - ./nginx.conf:/etc/nginx/nginx.conf
    - /home/hugh/Downloads:/usr/share/nginx/html/data
  ports:
    - "8080:8080"
  command: [nginx,'-g','daemon off;']  